### ISSUE TITLE
What if I Insert any vowel with capital letter like A ,etc ? 

### ISSUE THREAD

**Issue by moatasemelsayed** [Davenchy/embedded_linux_diploma_2023#1]
https://github.com/Davenchy/embedded_linux_diploma_2023/blob/bfa63638ca1fe8d6a2338b64b749f71dd249dc37/01_python/01_introduction/is_vowel_task2.py#L13

but anyway I would like to thank you you solve all of tasks with very high professional techniques so Thank you

**Comment by Davenchy** [comment]
Thank you for your feedback ❤️.
About the capital letter case
https://github.com/Davenchy/embedded_linux_diploma_2023/blob/bfa63638ca1fe8d6a2338b64b749f71dd249dc37/01_python/01_introduction/is_vowel_task2.py#L5

At the function `is_vowel` it converts the input into a lower case then checks if the letter is a vowel


```python
def is_vowel(letter): 
     return letter.lower() in ['a', 'e', 'i', 'o', 'u']
```

**Comment by Davenchy** [comment]
Also I added doctest to the function in commit b8860ef
